### ISSUE TITLE
Please don't use the AcoustID test API key

### ISSUE THREAD

**Issue by lalinsky** [wo80/AcoustID.NET#2]
It seems that you are using the test API key in https://github.com/wo80/AcoustID.NET/blob/master/Fingerprinter/MainForm.cs#L94

The API key might stop working at any time, please either register a new one or make it completely configurable.

**Comment by wo80** [comment]
On the one hand, since my "Fingerprinter" app is just for testing purpose, I think people who want to try the code should not be bothered with finding/getting an API key.

On the other hand, I'm aware that using the test key isn't a good idea. But getting a separate API key for the test app would just mean, having another AcoustID key in a public repository.

If this doesn't bother you, I'll register a separate key for the app.

Alternatively, the user could be prompted for a key on the first request to the service, with a link to your AcoustID website, where they can find the test key.

I guess you prefer the latter?

**Comment by lalinsky** [comment]
The best is to just register the app and add the API key to the repository. All open source apps have this problem, so that's fine.

**Comment by wo80** [comment]
Ok, got the key. I'll update the code asap.

**Comment by lalinsky** [comment]
Thanks.

**Comment by wo80** [comment]
Fixed in commit 1ba3953067aa79fb6c606364256c841159dca1e8
