### ISSUE TITLE
Creating fingerprints.

### ISSUE THREAD

**Issue by Iztral** [wo80/AcoustID.NET#6]
I'm developing a C# app that scans your local library, searches for matching songs in Spotify and adds them to a playlist. At this moment it uses just the file name or MP3 tags to match the songs. I would like to expand it with comparing audio fingerprints for files with missing tags or names.
From what I gathered the only example how to do this was deleted and I can't find anything that would explain how to do it. Is there an easy way to just create a fingerprint from a path, compare it with the database and get a possible song tile and author in return?

**Comment by wo80** [comment]
There's an example on how to implement the `IDecoder` interface in the [wiki](https://github.com/wo80/AcoustID.NET/wiki). It uses [NAudio](https://github.com/naudio/NAudio) for audio decoding. Use it like this:
```c#
var decoder = new NAudioDecoder(filename);
var context = new ChromaContext();

context.Start(decoder.SampleRate, decoder.Channels);
decoder.Decode(context.Consumer, 120);
context.Finish();

var fp = context.GetFingerprint();
```

I deleted the example app because the code was kind of a mess. You can still find it in the [commit history](https://github.com/wo80/AcoustID.NET/blob/b38ff5aa4dc438fbc09b3da072846ffe00055ec3/Fingerprinter/MainForm.cs).
