### ISSUE TITLE
NAudio decoder 24bit

### ISSUE THREAD

**Issue by soad-boon** [wo80/AcoustID.NET#8]
I am currently tinkering with your project and using the NAudio decoder. I noticed that the NAudio decoder is only working for 16bit WAV files.
I was trying to adapt the code in order to get it to work with 24bit files as well but without success. I get different hashes for the 16bit and 24bit file. Can you please guide me what needs to be done in order to support 24bit WAV for the NAudio decoder?

**Comment by wo80** [comment]
Chromaprint expects 16bit samples, so you'll have to convert the 24bit input to 16bit manually. In the `NAudioDecoder`, instead of the block copy
```c#
Buffer.BlockCopy(buffer, 0, data, 0, size);
```
you will have to take 3 bytes of your input `buffer` and convert to 2 bytes, either by discarding the least significant byte ([example](http://www.un4seen.com/forum/?topic=16948.0)) or by converting to 4 byte int and then converting to 2 byte short/float ([example](https://github.com/naudio/NAudio/blob/master/NAudio.Core/Wave/WaveStreams/WaveFileReader.cs#L221-L225)).

There's also a pull request adding `Wave24ToFloatProvider` (using the 4 byte cast to float approach), but I guess doing it as suggested above will give better performance: https://github.com/naudio/NAudio/pull/436

I currently don't have the time to test this. If you get this working, please post your code so I can add it to the wiki page.

**Comment by wo80** [comment]
Here's gist to get started (not tested): https://gist.github.com/wo80/1b9114bc70d1ef45ffda8f86b9fb6867

**Comment by wo80** [comment]
@soad-boon Any progress?
